CREATE TABLE "U" (
	"U_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"SUBJECT_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"REGION_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"POSITION_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"TIME_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"DOMAIN_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"U_NAME"	VARCHAR2(20)		NOT NULL,
	"U_NICKNAME"	VARCHAR2(20)		NOT NULL,
	"U_TEL"	VARCHAR2(20)		NOT NULL,
	"U_EMAIL"	VARCHAR2(50)		NOT NULL,
	"U_INTRO"	VARCHAR2(100)		NULL,
	"U_PORTFOLIO_URL"	VARCHAR2(100)		NULL,
	"U_ID"	VARCHAR2(20)		NOT NULL,
	"U_PW"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "C" (
	"C_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"DOMAIN_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"C_BUSINESS_NUMBER"	VARCHAR2(50)		NOT NULL,
	"C_INTRO"	VARCHAR2(500)		NOT NULL,
	"C_IDEAL"	VARCHAR2(100)		NULL,
	"C_PROJECT"	VARCHAR2(500)		NULL,
	"C_POSITION"	VARCHAR2(50)		NOT NULL,
	"C_NAME"	VARCHAR2(20)		NOT NULL,
	"C_EMAIL"	VARCHAR2(50)		NOT NULL,
	"C_ID"	VARCHAR2(20)		NOT NULL,
	"C_PW"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "A" (
	"A_CODE"	VARCHAR2(10)		NOT NULL,
	"A_ID"	VARCHAR2(20)		NOT NULL,
	"A_PW"	VARCHAR2(20)		NOT NULL,
	"A_SIGNUP_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "A"."A_CODE" IS '관리자 코드';

COMMENT ON COLUMN "A"."A_ID" IS '관리자 계정 ID';

COMMENT ON COLUMN "A"."A_PW" IS '관리자 계정 PW';

COMMENT ON COLUMN "A"."A_SIGNUP_DATE" IS '관리자 가입 일시';

CREATE TABLE "PH_L_EMAIL" (
	"PH_L_E_CODE"	VARCHAR2(10)		NOT NULL,
	"RECEIVE_U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"SEND_U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_L_EMAIL_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"PH_L_EMAIL_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "PH_L_EMAIL"."RECEIVE_U_P_APPLY_CODE" IS '수신자';

COMMENT ON COLUMN "PH_L_EMAIL"."SEND_U_P_APPLY_CODE" IS '발신자';

CREATE TABLE "S" (
	"S_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"SUBJECT_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"POSITION_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"REGION_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"TIME_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"DOMAIN_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"SNS_TYPE_CODE"	VARCHAR2(10)		NOT NULL,
	"S_NAME"	VARCHAR2(20)		NOT NULL,
	"S_NICKNAME"	VARCHAR2(20)		NOT NULL,
	"S_TEL"	VARCHAR2(20)		NOT NULL,
	"S_EMAIL"	VARCHAR2(50)		NOT NULL,
	"S_INTRO"	VARCHAR2(100)		NULL,
	"S_PORTFOLIO_URL"	VARCHAR2(100)		NULL,
	"S_ID"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "P" (
	"P_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"REGION_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"PLATFORM_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"SKILL_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"DEPARTMENT_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"SUBJECT_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"P_NAME"	VARCHAR2(30)		NOT NULL,
	"P_START_DATE"	DATE		NOT NULL,
	"P_END_DATE"	DATE		NOT NULL,
	"PJ_START_DATE"	DATE		NOT NULL,
	"PJ_END_DATE"	DATE		NOT NULL,
	"P_INFO-CONTENT"	VARCHAR2(4000)		NOT NULL,
	"P_INFO_REFO"	VARCHAR2(100)		NULL,
	"P_UPDATE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "P"."USER_CODE" IS '개설자';

CREATE TABLE "REGION_PART" (
	"REGION_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"REGION_PART"	VARCHAR2(10)		NOT NULL
);

CREATE TABLE "TIME_PART" (
	"TIME_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"TIME_PART"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "TIME_PART"."TIME_PART" IS '오전, 오후';

CREATE TABLE "DOMAIN_PART" (
	"DOMAIN_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"DOMAIN_ADDRESS"	VARCHAR2(20)		NOT NULL,
	"DOMAIN_PART"	VARCHAR2(10)		NOT NULL
);

CREATE TABLE "REPORT_REASON" (
	"REPORT_REASON_CODE"	VARCHAR2(10)		NOT NULL,
	"REPORT_REASON"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "SUBJECT_PART" (
	"SUBJECT_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"SUBJECT_PART"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "SUBJECT_PART"."SUBJECT_PART" IS '프로젝트 대분류';

CREATE TABLE "DEPARTMENT_PART" (
	"DEPARTMENT_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"DEPARTMENT_PART"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "DEPARTMENT_PART"."DEPARTMENT_PART" IS '프로젝트 소분류';

CREATE TABLE "PLATFORM_PART" (
	"PLATFORM_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"PLATFORM_PART"	VARCHAR2(50)		NOT NULL
);

CREATE TABLE "CS_FAQ" (
	"CS_FAQ_CODE"	VARCHAR2(10)		NOT NULL,
	"A_CODE"	VARCHAR2(10)		NOT NULL,
	"CS_FAQ_TITLE"	VARCHAR2(30)		NOT NULL,
	"CS_FAQ_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CS_FAQ_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "CS_FAQ"."CS_FAQ_CONTENT" IS 'FAQ 내용';

CREATE TABLE "POSITION_PART" (
	"POSITION_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"POSITION_PART"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "POSITION_PART"."POSITION_PART" IS 'UI/UX, 기획 등 모집 분야';

CREATE TABLE "SKILL_PART" (
	"SKILL_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"SKILL_PART"	VARCHAR2(50)		NOT NULL
);

CREATE TABLE "P_OUT_REASON" (
	"P_OUT_REASON_CODE"	VARCHAR2(10)		NOT NULL,
	"P_OUT_REASON"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "PENALTY_PART" (
	"PENALTY_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"PENALTY_PART"	VARCHAR2(50)		NOT NULL
);

CREATE TABLE "USER_PENALTY" (
	"USER_PENALTY_CODE"	VARCHAR2(10)		NOT NULL,
	"PENALTY_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_PANALTY_DATE"	DATE		NOT NULL
);

CREATE TABLE "L_POST_FILE" (
	"L_POST_FILE_CODE"	VARCHAR2(10)		NOT NULL,
	"L_POST_CODE"	VARCHAR2(10)		NOT NULL,
	"L_POST_FILE_PATH"	VARCHAR2(100)		NOT NULL,
	"L_POST_FILE_NAME"	VARCHAR2(50)		NOT NULL,
	"L_POST_FILE_SIZE"	NUMBER(11,2)		NOT NULL,
	"L_POST_FILE_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "L_POST_FILE"."L_POST_FILE_PATH" IS '파일 경로';

COMMENT ON COLUMN "L_POST_FILE"."L_POST_FILE_NAME" IS '서버에 저장된 파일이름';

COMMENT ON COLUMN "L_POST_FILE"."L_POST_FILE_SIZE" IS '파일 사이즈';

COMMENT ON COLUMN "L_POST_FILE"."L_POST_FILE_DATE" IS '파일등록일자';

CREATE TABLE "L_POST" (
	"L_POST_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"L_POST_TITLE"	VARCHAR2(30)		NOT NULL,
	"L_POST_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"L_POST_ADD_DATE"	DATE		NOT NULL,
	"L_POST_UPDATE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "L_POST"."USER_CODE" IS '작성자';

CREATE TABLE "REPORT_POST" (
	"REPORT_POST_CODE"	VARCHAR2(10)		NOT NULL,
	"L_POST_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"REPORT_REASON_CODE"	VARCHAR2(10)		NOT NULL,
	"A_CODE"	VARCHAR2(10)		NOT NULL,
	"WARNED_POST_CODE"	VARCHAR2(10)		NULL,
	"REPORT_DATE"	DATE		NOT NULL,
	"REPORT_COMPLETE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "REPORT_POST"."USER_CODE" IS '신고자';

CREATE TABLE "PH_MEET" (
	"PH_MEET_CODE"	VARCHAR2(10)		NOT NULL,
	"U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_MEET_TITLE"	VARCHAR2(30)		NOT NULL,
	"PH_MEET_SUBTITLE"	VARCHAR2(30)		NOT NULL,
	"PH_MEET_START_DATE"	DATE		NOT NULL,
	"PH_MEET_END_DATE"	DATE		NOT NULL,
	"PH_MEET_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"PH_MEET_DATE"	DATE		NOT NULL,
	"PH_MEET_UPDATE_DATE"	DATE		NULL
);

CREATE TABLE "P_LIKE" (
	"P_LIKE_CODE"	VARCHAR2(10)		NOT NULL,
	"P_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"P_LIKE_DATE"	DATE		NOT NULL
);

CREATE TABLE "PH_MAINWORK" (
	"PH_MAINWORK_CODE"	VARCHAR2(10)		NOT NULL,
	"U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_MAINWORK_START_DATE"	DATE		NOT NULL,
	"PH_MAINWORK_END_DATE"	DATE		NOT NULL,
	"PH_MAINWORK_DATE"	DATE		NOT NULL,
	"PH_MAINWORK_UPDATE_DATE"	DATE		NULL
);

CREATE TABLE "PH_SUBWORK" (
	"PH_SUBWORK_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_MAINWORK_CODE"	VARCHAR2(10)		NOT NULL,
	"U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_SUBWORK_TITLE"	VARCHAR2(30)		NOT NULL,
	"PH_SUBWORK_DETAIL"	VARCHAR2(100)		NULL,
	"PH_SUBWORK_START_DATE"	DATE		NOT NULL
);

CREATE TABLE "PH_L_VOTE" (
	"PH_L_VOTE_CODE"	VARCHAR2(10)		NOT NULL,
	"U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_L_VOTE_TITLE"	VARCHAR2(30)		NOT NULL,
	"PH_L_VOTE_START_DATE"	DATE		NOT NULL,
	"PH_L_VOTE_END_DATE"	DATE		NOT NULL
);

CREATE TABLE "PH_CAL" (
	"PH_CAL_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_CAL_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_CAL_TITLE"	VARCHAR2(30)		NOT NULL,
	"PH_CAL_START_DATE"	DATE		NOT NULL,
	"PH_CAL_END_DATE"	DATE		NOT NULL,
	"PH_CAL_INSERT_DATE"	DATE		NOT NULL
);

CREATE TABLE "SNS_TYPE" (
	"SNS_TYPE_CODE"	VARCHAR2(10)		NOT NULL,
	"SNS_TYPE"	VARCHAR2(10)		NOT NULL
);

CREATE TABLE "USER_MAIN" (
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_SIGNUP_DATE"	VARCHAR(10)		NOT NULL
);

CREATE TABLE "WITHDRAW" (
	"WITHDRAW_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"WITHDRAW_ID"	VARCHAR2(20)		NOT NULL,
	"WITHDRAW_EMAIL"	VARCHAR2(50)		NOT NULL,
	"WITHDRAW_NAME"	VARCHAR2(20)		NOT NULL,
	"WITHDRAW_REASON"	VARCHAR2(100)		NOT NULL,
	"WITHDRAW_DATE"	DATE		NOT NULL
);

CREATE TABLE "USER_DORMANT" (
	"USER_DORMANT_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_DORMANT_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "USER_DORMANT"."USER_DORMANT_CODE" IS '휴면회원 코드';

CREATE TABLE "P_OUT" (
	"P_OUT_CODE"	VARCHAR2(10)		NOT NULL,
	"P_OUT_REASON_CODE"	VARCHAR2(10)		NOT NULL,
	"U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"P_OUT_DATE"	DATE		NOT NULL
);

CREATE TABLE "U_SKILL" (
	"U_SKILL_CODE"	VARCHAR2(10)		NOT NULL,
	"SKILL_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"U_SKILL_PART_CODE"	VARCHAR2(10)		NOT NULL
);

CREATE TABLE "USER_LOGIN_LOG" (
	"USER_LOGIN_LOG_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_LOGIN_LOG_DATE"	DATE		NULL
);

CREATE TABLE "POST_LIKE" (
	"POST_LIKE_CODE"	VARCHAR2(10)		NOT NULL,
	"L_POST_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"POST_LIKE_DATE"	DATE		NOT NULL
);

CREATE TABLE "U_LIKE" (
	"U_LIKE_CODE"	VARCHAR2(10)		NOT NULL,
	"RECEIVE_USER_CODE"	VARCHAR2(10)		NOT NULL,
	"SEND_USER_CODE"	VARCHAR2(10)		NOT NULL,
	"U_LIKE_DATE"	DATE		NOT NULL,
	"U_LIKE_REASON"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "U_LIKE"."RECEIVE_USER_CODE" IS '좋아요 받은 회원';

COMMENT ON COLUMN "U_LIKE"."SEND_USER_CODE" IS '좋아요 한 회원';

CREATE TABLE "PH_L_POST" (
	"PH_L_POST_CODE"	VARCHAR2(10)		NOT NULL,
	"U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_L_POST_TITLE"	VARCHAR(30)		NOT NULL,
	"PH_L_POST_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"PH_L_POST_DATE"	DATE		NOT NULL,
	"PH_L_POST_UPDATE_DATE"	DATE		NULL
);

CREATE TABLE "P_PLUS" (
	"P_PLUS_CODE"	VARCHAR2(10)		NOT NULL,
	"P_CODE"	VARCHAR2(10)		NOT NULL,
	"P_PLUS_DATE"	DATE		NOT NULL
);

CREATE TABLE "BANNER_FILE" (
	"BANNER_FILE_CODE"	VARCHAR2(10)		NOT NULL,
	"A_CODE"	VARCHAR2(10)		NOT NULL,
	"BANNER_FILE_PATH"	VARCHAR2(500)		NOT NULL,
	"BANNER_FILE_NAME"	VARCHAR2(50)		NOT NULL,
	"BANNER_FILE_SIZE"	NUMBER(11,2)		NOT NULL,
	"BANNER_FILE_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "BANNER_FILE"."BANNER_FILE_PATH" IS '파일 저장 경로';

COMMENT ON COLUMN "BANNER_FILE"."BANNER_FILE_NAME" IS '서버에 저장된 파일 이름';

COMMENT ON COLUMN "BANNER_FILE"."BANNER_FILE_SIZE" IS '파일 사이즈';

COMMENT ON COLUMN "BANNER_FILE"."BANNER_FILE_DATE" IS '파일 등록 일자';

CREATE TABLE "P_FAILED" (
	"P_FAILED_CODE"	VARCHAR2(10)		NOT NULL,
	"P_CODE"	VARCHAR2(10)		NOT NULL,
	"P_FAILED_DATE"	DATE		NOT NULL
);

CREATE TABLE "PH_S_COMMENT" (
	"PH_S_COMMENT_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_SUBWORK_COMPLETE_CODE"	VARCHAR2(10)		NOT NULL,
	"U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_S_COMMENT_CONTENT"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "PH_L_POST_COMMENT" (
	"PH_L_POST_COMMENT_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_L_POST_CODE"	VARCHAR2(10)		NOT NULL,
	"U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_L_POST_COMMENT_CODE2"	VARCHAR2(10)		NOT NULL,
	"PH_L_POST_COMMENT_CONTENT"	VARCHAR2(100)		NOT NULL,
	"PH_L_POST_COMMENT_DATE"	DATE		NOT NULL,
	"PH_L_POST_COMMENT_UPDATE_DATE"	DATE		NULL,
	"PH_L_POST_COMMENT_DEPTH"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "PH_L_POST_COMMENT"."U_P_APPLY_CODE" IS '작성자';

COMMENT ON COLUMN "PH_L_POST_COMMENT"."PH_L_POST_COMMENT_CODE2" IS '모댓글';

COMMENT ON COLUMN "PH_L_POST_COMMENT"."PH_L_POST_COMMENT_DEPTH" IS '댓글의 계층';

CREATE TABLE "REPORT_P" (
	"REPORT_P_CODE"	VARCHAR2(10)		NOT NULL,
	"P_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"REPORT_REASON_CODE"	VARCHAR2(10)		NOT NULL,
	"A_CODE"	VARCHAR2(10)		NOT NULL,
	"WARNED_POST_CODE"	VARCHAR2(10)		NULL,
	"REPORT_P_DATE"	DATE		NOT NULL,
	"REPORT_DATE"	DATE		NOT NULL,
	"REPORT_COMPLETE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "REPORT_P"."USER_CODE" IS '신고자';

CREATE TABLE "REPORT_P_COMPLETE" (
	"REPORT_P_COMPLETE_CODE"	VARCHAR2(10)		NOT NULL,
	"P_END_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"REPORT_REASON_CODE"	VARCHAR2(10)		NOT NULL,
	"A_CODE"	VARCHAR2(10)		NOT NULL,
	"WARNED_POST_CODE"	VARCHAR2(10)		NULL,
	"REPORT_P_COMPETE_DATE"	DATE		NOT NULL,
	"REPORT_DATE"	DATE		NOT NULL,
	"REPORT_COMPLETE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "REPORT_P_COMPLETE"."USER_CODE" IS '신고자';

CREATE TABLE "CS_QNA_COMPLETE" (
	"CS_QNA_COMPLETE_CODE"	VARCHAR2(10)		NOT NULL,
	"CS_QNA_CODE"	VARCHAR2(10)		NOT NULL,
	"A_CODE"	VARCHAR2(10)		NOT NULL,
	"CS_QNA_COMPLETE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CS_QNA_COMPLETE_DATE"	DATE		NOT NULL
);

CREATE TABLE "QNA_PART" (
	"QNA_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"QNA_PART"	VARCHAR2(50)		NOT NULL
);

CREATE TABLE "CS_QNA" (
	"CS_QNA_CODE"	VARCHAR2(10)		NOT NULL,
	"QNA_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"CS_QNA_TITLE"	VARCHAR2(30)		NOT NULL,
	"CS_QNA_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CS_QNA_DATE"	DATE		NOT NULL,
	"CS_QNA_UPDATE_DATE"	DATE		NULL
);

CREATE TABLE "L_POST_COMMENT" (
	"L_POST_COMMENT_CODE"	VARCHAR2(10)		NOT NULL,
	"L_POST_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"L_POST_COMMENT_CODE2"	VARCHAR2(10)		NOT NULL,
	"L_POST_COMMENT_CONTENT"	VARCHAR2(100)		NOT NULL,
	"L_POST_COMMENT_DATE"	DATE		NOT NULL,
	"L_POST_COMMENT_UPDATE_DATE"	DATE		NULL,
	"L_POST_COMMENT_DEPTH"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "L_POST_COMMENT"."L_POST_COMMENT_CODE2" IS '부모댓글';

COMMENT ON COLUMN "L_POST_COMMENT"."L_POST_COMMENT_DEPTH" IS '계층';

CREATE TABLE "PH_MEET_FILE" (
	"PH_MEET_FILE_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_MEET_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_MEET_FILE_PATH"	VARCHAR2(100)		NOT NULL,
	"PH_MEET_FILE_NAME"	VARCHAR2(50)		NOT NULL,
	"PH_MEET_FILE_SIZE"	NUMBER(11,2)		NOT NULL,
	"PH_MEET_FILE_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "PH_MEET_FILE"."PH_MEET_FILE_PATH" IS '파일 경로';

COMMENT ON COLUMN "PH_MEET_FILE"."PH_MEET_FILE_NAME" IS '서버에 저장된 파일이름';

COMMENT ON COLUMN "PH_MEET_FILE"."PH_MEET_FILE_SIZE" IS '파일 사이즈';

COMMENT ON COLUMN "PH_MEET_FILE"."PH_MEET_FILE_DATE" IS '파일등록일자';

CREATE TABLE "PH_MAINWORK_FILE" (
	"PH_MAINWORK_FILE_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_MAINWORK_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_MAINWORK_FILE_PATH"	VARCHAR2(100)		NOT NULL,
	"PH_MAINWORK_FILE_NAME"	VARCHAR2(50)		NOT NULL,
	"PH_MAINWORK_FILE_SIZE"	NUMBER(11,2)		NOT NULL,
	"PH_MAINWORK_FILE_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "PH_MAINWORK_FILE"."PH_MAINWORK_FILE_PATH" IS '파일 경로';

COMMENT ON COLUMN "PH_MAINWORK_FILE"."PH_MAINWORK_FILE_NAME" IS '서버에 저장된 파일이름';

COMMENT ON COLUMN "PH_MAINWORK_FILE"."PH_MAINWORK_FILE_SIZE" IS '파일 사이즈';

COMMENT ON COLUMN "PH_MAINWORK_FILE"."PH_MAINWORK_FILE_DATE" IS '파일등록일자';

CREATE TABLE "L_NOTICE" (
	"L_NOTICE_CODE"	VARCHAR2(10)		NOT NULL,
	"A_CODE"	VARCHAR2(10)		NOT NULL,
	"L_NOTICE_TITLE"	VARCHAR2(40)		NOT NULL,
	"L_NOTICE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"L_NOTICE_DATE"	DATE		NOT NULL,
	"L_NOTICE_UPDATE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "L_NOTICE"."L_NOTICE_UPDATE_DATE" IS '공지사항 최종 수정일시';

CREATE TABLE "PH_L_VOTE_CHOICE" (
	"PH_L_VOTE_CHOICE_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_L_VOTE_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_L_VOTE_CHOICE"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "PH_L_VOTE_CHOICE"."PH_L_VOTE_CHOICE" IS '투표문항';

CREATE TABLE "P_RATING" (
	"P_RATING_CODE"	VARCHAR2(10)		NOT NULL,
	"RECEIVE_U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"SEND_U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"P_RATING"	NUMBER		NOT NULL,
	"P_RATING_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "P_RATING"."RECEIVE_U_P_APPLY_CODE" IS '평가대상회원';

COMMENT ON COLUMN "P_RATING"."SEND_U_P_APPLY_CODE" IS '평가받는회원';

COMMENT ON COLUMN "P_RATING"."P_RATING" IS '0.5~5';

CREATE TABLE "P_NEWS" (
	"P_NEWS_CODE"	VARCHAR2(10)		NOT NULL,
	"P_CODE"	VARCHAR2(10)		NOT NULL,
	"P_NEWS_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"P_NEWS_DATE"	DATE		NOT NULL
);

CREATE TABLE "C_EMAIL" (
	"C_EMAIL_CODE"	VARCHAR2(10)		NOT NULL,
	"C_CODE"	VARCHAR2(10)		NOT NULL,
	"U_LIKE_CODE"	VARCHAR2(10)		NOT NULL,
	"C_EMAIL_DATE"	DATE		NOT NULL,
	"C_EMAIL_CONTENT"	VARCHAR2(4000)		NULL
);

CREATE TABLE "WANRED_U" (
	"WARNED_U_CODE"	VARCHAR2(10)		NOT NULL,
	"REPORT_REASON_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"WARNED_U_DATE"	DATE		NOT NULL
);

CREATE TABLE "PH_L_POST_FILE" (
	"PH_L_POST_FILE_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_L_POST_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_L_POST_FILE_PATH"	VARCHAR2(100)		NOT NULL,
	"PH_L_POST_FILE_NAME"	VARCHAR2(50)		NOT NULL,
	"PH_L_POST_FILE_SIZE"	NUMBER(11,2)		NOT NULL,
	"PH_L_POST_FILE_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "PH_L_POST_FILE"."PH_L_POST_FILE_PATH" IS '파일 경로';

COMMENT ON COLUMN "PH_L_POST_FILE"."PH_L_POST_FILE_NAME" IS '서버에 저장된 파일이름';

COMMENT ON COLUMN "PH_L_POST_FILE"."PH_L_POST_FILE_SIZE" IS '파일 사이즈';

COMMENT ON COLUMN "PH_L_POST_FILE"."PH_L_POST_FILE_DATE" IS '파일등록일자';

CREATE TABLE "PH_SUBWORK_COMPLETE" (
	"PH_SUBWORK_COMPLETE_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_SUBWORK_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_SUBWORK_COMPLETE"	DATE		NOT NULL
);

CREATE TABLE "L_NOTICE_FILE" (
	"L_NOTICE_FILE_CODE"	VARCHAR2(10)		NOT NULL,
	"L_NOTICE_CODE"	VARCHAR2(10)		NOT NULL,
	"L_NOTICE_FILE_PATH"	VARCHAR2(500)		NOT NULL,
	"I_NOTICE_FILE_NAME"	VARCHAR2(50)		NOT NULL,
	"L_NOTICE_FILE_SIZE"	NUMBER(11,2)		NOT NULL,
	"L_NOTICE_FILE_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "L_NOTICE_FILE"."L_NOTICE_FILE_PATH" IS '파일 저장 경로';

COMMENT ON COLUMN "L_NOTICE_FILE"."I_NOTICE_FILE_NAME" IS '서버에 저장된 파일 이름';

COMMENT ON COLUMN "L_NOTICE_FILE"."L_NOTICE_FILE_SIZE" IS '파일 사이즈';

COMMENT ON COLUMN "L_NOTICE_FILE"."L_NOTICE_FILE_DATE" IS '파일 등록 일자';

CREATE TABLE "P_POSITION" (
	"P_POSITION_CODE"	VARCHAR2(10)		NOT NULL,
	"POSITION_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"P_CODE"	VARCHAR2(10)		NOT NULL,
	"P_POSITION_COUNT"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "P_POSITION"."P_POSITION_COUNT" IS '디폴트 1?';

CREATE TABLE "REPORT_COMMENT" (
	"REPORT_COMMENT_CODE"	VARCHAR2(10)		NOT NULL,
	"REPORT_REASON_CODE"	VARCHAR2(10)		NOT NULL,
	"L_POST_COMMENT_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"A_CODE"	VARCHAR2(10)		NOT NULL,
	"WARNED_POST_CODE"	VARCHAR2(10)		NULL,
	"REPORT_DATE"	DATE		NOT NULL,
	"REPORT_COMPLETE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "REPORT_COMMENT"."USER_CODE" IS '신고자';

CREATE TABLE "P_TEAM_CONFIRM" (
	"P_TEAM_CONFIRM_CODE"	VARCHAR2(10)		NOT NULL,
	"P_CODE"	VARCHAR2(10)		NOT NULL,
	"P_TEAM_CONFIRM_DATE"	DATE		NOT NULL
);

CREATE TABLE "P_REJECT" (
	"P_REJECT_CODE"	VARCHAR2(10)		NOT NULL,
	"U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"REJECT_CONDITION_CODE"	VARCHAR2(10)		NOT NULL,
	"P_REJECT_DATE"	DATE		NOT NULL
);

CREATE TABLE "P_READER" (
	"P_READER_CODE"	VARCHAR2(10)		NOT NULL,
	"U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"P_READER_DATE"	DATE		NOT NULL,
	"P_READER_REASON"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "P_READER"."U_P_APPLY_CODE" IS '직무지원코드';

CREATE TABLE "PH_MEET_MEMBER" (
	"PH_MEET_MEMBER_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_MEET_CODE"	VARCHAR2(10)		NOT NULL,
	"U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL
);

CREATE TABLE "PH_CAL_PART" (
	"PH_CAL_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_CAL_PART"	VARCHAR2(10)		NOT NULL
);

CREATE TABLE "U_P_APPLY" (
	"U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"P_POSITION_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"U_P_APPLY_REASON"	VARCHAR2(100)		NULL,
	"U_P_APPLY_DATE"	DATE		NOT NULL,
	"U_P_READY_DATE"	DATE		NULL
);

COMMENT ON COLUMN "U_P_APPLY"."USER_CODE" IS '지원사유';

COMMENT ON COLUMN "U_P_APPLY"."U_P_APPLY_REASON" IS '팀장은 null';

CREATE TABLE "REJECT_CONDITION" (
	"REJECT_CONDITION_CODE"	VARCHAR2(10)		NOT NULL,
	"REJECT_CONDITION"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "REJECT_CONDITION"."REJECT_CONDITION" IS '지원 거절, 지원 차단';

CREATE TABLE "PH_L_VOTE_MEMBER" (
	"PH_L_VOTE_MEMBER_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_L_VOTE_CHOICE_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_L_VOTE_DATE"	DATE		NOT NULL
);

CREATE TABLE "PH_MAINWORK_MEMBER" (
	"PH_MAINWORK_MEMBER_CODE"	VARCHAR2(10)		NOT NULL,
	"U_P_APPLY_CODE"	VARCHAR2(10)		NOT NULL,
	"PH_MAINWORK_CODE"	VARCHAR2(10)		NOT NULL
);

CREATE TABLE "WARNED_POST" (
	"WARNED_POST_CODE"	VARCHAR2(10)		NOT NULL,
	"WARNED_PART"	VARCHAR2(50)		NOT NULL
);

CREATE TABLE "P_END_CONDITION" (
	"P_END_CONDITION_CODE"	VARCHAR2(10)		NOT NULL,
	"P_END_CONDITION"	VARCHAR2(10)		NOT NULL
);

CREATE TABLE "USER_NOTIFICATION" (
	"USER_NOTIFICATION_CODE"	VARCHAR2(10)		NOT NULL,
	"USER_CODE"	VARCHAR(10)		NOT NULL,
	"USER_NOTIFICATION_CHECK_DATE"	DATE		NULL
);

CREATE TABLE "P_END" (
	"P_END_CODE"	VARCHAR2(10)		NOT NULL,
	"P_TEAM_CONFIRM_CODE"	VARCHAR2(10)		NOT NULL,
	"P_END_CONDITION_CODE"	VARCHAR2(10)		NOT NULL,
	"P_END_DATE"	DATE		NOT NULL
);

CREATE TABLE "U_SKILL_PART" (
	"U_SKILL_PART_CODE"	VARCHAR2(10)		NOT NULL,
	"U_SKILL_PART"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "U_SKILL_PART"."U_SKILL_PART" IS '메인인지 서브인지 구분';

CREATE TABLE "P_FILE" (
	"P_FILE_CODE"	VARCHAR2(10)		NOT NULL,
	"P_CODE"	VARCHAR2(10)		NOT NULL,
	"P_FILE_PATH"	VARCHAR2(100)		NOT NULL,
	"P_FILE_NAME"	VARCHAR2(50)		NOT NULL,
	"P_FILE_SIZE"	NUMBER(11,2)		NOT NULL,
	"P_FILE_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "P_FILE"."P_FILE_PATH" IS '파일 경로';

COMMENT ON COLUMN "P_FILE"."P_FILE_NAME" IS '서버에 저장된 파일이름';

COMMENT ON COLUMN "P_FILE"."P_FILE_SIZE" IS '파일 사이즈';

COMMENT ON COLUMN "P_FILE"."P_FILE_DATE" IS '파일등록일자';

ALTER TABLE "U" ADD CONSTRAINT "PK_U" PRIMARY KEY (
	"U_CODE"
);

ALTER TABLE "C" ADD CONSTRAINT "PK_C" PRIMARY KEY (
	"C_CODE"
);

ALTER TABLE "A" ADD CONSTRAINT "PK_A" PRIMARY KEY (
	"A_CODE"
);

ALTER TABLE "PH_L_EMAIL" ADD CONSTRAINT "PK_PH_L_EMAIL" PRIMARY KEY (
	"PH_L_E_CODE"
);

ALTER TABLE "S" ADD CONSTRAINT "PK_S" PRIMARY KEY (
	"S_CODE"
);

ALTER TABLE "P" ADD CONSTRAINT "PK_P" PRIMARY KEY (
	"P_CODE"
);

ALTER TABLE "REGION_PART" ADD CONSTRAINT "PK_REGION_PART" PRIMARY KEY (
	"REGION_PART_CODE"
);

ALTER TABLE "TIME_PART" ADD CONSTRAINT "PK_TIME_PART" PRIMARY KEY (
	"TIME_PART_CODE"
);

ALTER TABLE "DOMAIN_PART" ADD CONSTRAINT "PK_DOMAIN_PART" PRIMARY KEY (
	"DOMAIN_PART_CODE"
);

ALTER TABLE "REPORT_REASON" ADD CONSTRAINT "PK_REPORT_REASON" PRIMARY KEY (
	"REPORT_REASON_CODE"
);

ALTER TABLE "SUBJECT_PART" ADD CONSTRAINT "PK_SUBJECT_PART" PRIMARY KEY (
	"SUBJECT_PART_CODE"
);

ALTER TABLE "DEPARTMENT_PART" ADD CONSTRAINT "PK_DEPARTMENT_PART" PRIMARY KEY (
	"DEPARTMENT_PART_CODE"
);

ALTER TABLE "PLATFORM_PART" ADD CONSTRAINT "PK_PLATFORM_PART" PRIMARY KEY (
	"PLATFORM_PART_CODE"
);

ALTER TABLE "CS_FAQ" ADD CONSTRAINT "PK_CS_FAQ" PRIMARY KEY (
	"CS_FAQ_CODE"
);

ALTER TABLE "POSITION_PART" ADD CONSTRAINT "PK_POSITION_PART" PRIMARY KEY (
	"POSITION_PART_CODE"
);

ALTER TABLE "SKILL_PART" ADD CONSTRAINT "PK_SKILL_PART" PRIMARY KEY (
	"SKILL_PART_CODE"
);

ALTER TABLE "P_OUT_REASON" ADD CONSTRAINT "PK_P_OUT_REASON" PRIMARY KEY (
	"P_OUT_REASON_CODE"
);

ALTER TABLE "PENALTY_PART" ADD CONSTRAINT "PK_PENALTY_PART" PRIMARY KEY (
	"PENALTY_PART_CODE"
);

ALTER TABLE "USER_PENALTY" ADD CONSTRAINT "PK_USER_PENALTY" PRIMARY KEY (
	"USER_PENALTY_CODE"
);

ALTER TABLE "L_POST_FILE" ADD CONSTRAINT "PK_L_POST_FILE" PRIMARY KEY (
	"L_POST_FILE_CODE"
);

ALTER TABLE "L_POST" ADD CONSTRAINT "PK_L_POST" PRIMARY KEY (
	"L_POST_CODE"
);

ALTER TABLE "REPORT_POST" ADD CONSTRAINT "PK_REPORT_POST" PRIMARY KEY (
	"REPORT_POST_CODE"
);

ALTER TABLE "PH_MEET" ADD CONSTRAINT "PK_PH_MEET" PRIMARY KEY (
	"PH_MEET_CODE"
);

ALTER TABLE "P_LIKE" ADD CONSTRAINT "PK_P_LIKE" PRIMARY KEY (
	"P_LIKE_CODE"
);

ALTER TABLE "PH_MAINWORK" ADD CONSTRAINT "PK_PH_MAINWORK" PRIMARY KEY (
	"PH_MAINWORK_CODE"
);

ALTER TABLE "PH_SUBWORK" ADD CONSTRAINT "PK_PH_SUBWORK" PRIMARY KEY (
	"PH_SUBWORK_CODE"
);

ALTER TABLE "PH_L_VOTE" ADD CONSTRAINT "PK_PH_L_VOTE" PRIMARY KEY (
	"PH_L_VOTE_CODE"
);

ALTER TABLE "PH_CAL" ADD CONSTRAINT "PK_PH_CAL" PRIMARY KEY (
	"PH_CAL_CODE"
);

ALTER TABLE "SNS_TYPE" ADD CONSTRAINT "PK_SNS_TYPE" PRIMARY KEY (
	"SNS_TYPE_CODE"
);

ALTER TABLE "USER_MAIN" ADD CONSTRAINT "PK_USER_MAIN" PRIMARY KEY (
	"USER_CODE"
);

ALTER TABLE "WITHDRAW" ADD CONSTRAINT "PK_WITHDRAW" PRIMARY KEY (
	"WITHDRAW_CODE"
);

ALTER TABLE "USER_DORMANT" ADD CONSTRAINT "PK_USER_DORMANT" PRIMARY KEY (
	"USER_DORMANT_CODE"
);

ALTER TABLE "P_OUT" ADD CONSTRAINT "PK_P_OUT" PRIMARY KEY (
	"P_OUT_CODE"
);

ALTER TABLE "U_SKILL" ADD CONSTRAINT "PK_U_SKILL" PRIMARY KEY (
	"U_SKILL_CODE"
);

ALTER TABLE "USER_LOGIN_LOG" ADD CONSTRAINT "PK_USER_LOGIN_LOG" PRIMARY KEY (
	"USER_LOGIN_LOG_CODE"
);

ALTER TABLE "POST_LIKE" ADD CONSTRAINT "PK_POST_LIKE" PRIMARY KEY (
	"POST_LIKE_CODE"
);

ALTER TABLE "U_LIKE" ADD CONSTRAINT "PK_U_LIKE" PRIMARY KEY (
	"U_LIKE_CODE"
);

ALTER TABLE "PH_L_POST" ADD CONSTRAINT "PK_PH_L_POST" PRIMARY KEY (
	"PH_L_POST_CODE"
);

ALTER TABLE "P_PLUS" ADD CONSTRAINT "PK_P_PLUS" PRIMARY KEY (
	"P_PLUS_CODE"
);

ALTER TABLE "BANNER_FILE" ADD CONSTRAINT "PK_BANNER_FILE" PRIMARY KEY (
	"BANNER_FILE_CODE"
);

ALTER TABLE "P_FAILED" ADD CONSTRAINT "PK_P_FAILED" PRIMARY KEY (
	"P_FAILED_CODE"
);

ALTER TABLE "PH_S_COMMENT" ADD CONSTRAINT "PK_PH_S_COMMENT" PRIMARY KEY (
	"PH_S_COMMENT_CODE"
);

ALTER TABLE "PH_L_POST_COMMENT" ADD CONSTRAINT "PK_PH_L_POST_COMMENT" PRIMARY KEY (
	"PH_L_POST_COMMENT_CODE"
);

ALTER TABLE "REPORT_P" ADD CONSTRAINT "PK_REPORT_P" PRIMARY KEY (
	"REPORT_P_CODE"
);

ALTER TABLE "REPORT_P_COMPLETE" ADD CONSTRAINT "PK_REPORT_P_COMPLETE" PRIMARY KEY (
	"REPORT_P_COMPLETE_CODE"
);

ALTER TABLE "CS_QNA_COMPLETE" ADD CONSTRAINT "PK_CS_QNA_COMPLETE" PRIMARY KEY (
	"CS_QNA_COMPLETE_CODE"
);

ALTER TABLE "QNA_PART" ADD CONSTRAINT "PK_QNA_PART" PRIMARY KEY (
	"QNA_PART_CODE"
);

ALTER TABLE "CS_QNA" ADD CONSTRAINT "PK_CS_QNA" PRIMARY KEY (
	"CS_QNA_CODE"
);

ALTER TABLE "L_POST_COMMENT" ADD CONSTRAINT "PK_L_POST_COMMENT" PRIMARY KEY (
	"L_POST_COMMENT_CODE"
);

ALTER TABLE "PH_MEET_FILE" ADD CONSTRAINT "PK_PH_MEET_FILE" PRIMARY KEY (
	"PH_MEET_FILE_CODE"
);

ALTER TABLE "PH_MAINWORK_FILE" ADD CONSTRAINT "PK_PH_MAINWORK_FILE" PRIMARY KEY (
	"PH_MAINWORK_FILE_CODE"
);

ALTER TABLE "L_NOTICE" ADD CONSTRAINT "PK_L_NOTICE" PRIMARY KEY (
	"L_NOTICE_CODE"
);

ALTER TABLE "PH_L_VOTE_CHOICE" ADD CONSTRAINT "PK_PH_L_VOTE_CHOICE" PRIMARY KEY (
	"PH_L_VOTE_CHOICE_CODE"
);

ALTER TABLE "P_RATING" ADD CONSTRAINT "PK_P_RATING" PRIMARY KEY (
	"P_RATING_CODE"
);

ALTER TABLE "P_NEWS" ADD CONSTRAINT "PK_P_NEWS" PRIMARY KEY (
	"P_NEWS_CODE"
);

ALTER TABLE "C_EMAIL" ADD CONSTRAINT "PK_C_EMAIL" PRIMARY KEY (
	"C_EMAIL_CODE"
);

ALTER TABLE "WANRED_U" ADD CONSTRAINT "PK_WANRED_U" PRIMARY KEY (
	"WARNED_U_CODE"
);

ALTER TABLE "PH_L_POST_FILE" ADD CONSTRAINT "PK_PH_L_POST_FILE" PRIMARY KEY (
	"PH_L_POST_FILE_CODE"
);

ALTER TABLE "PH_SUBWORK_COMPLETE" ADD CONSTRAINT "PK_PH_SUBWORK_COMPLETE" PRIMARY KEY (
	"PH_SUBWORK_COMPLETE_CODE"
);

ALTER TABLE "L_NOTICE_FILE" ADD CONSTRAINT "PK_L_NOTICE_FILE" PRIMARY KEY (
	"L_NOTICE_FILE_CODE"
);

ALTER TABLE "P_POSITION" ADD CONSTRAINT "PK_P_POSITION" PRIMARY KEY (
	"P_POSITION_CODE"
);

ALTER TABLE "REPORT_COMMENT" ADD CONSTRAINT "PK_REPORT_COMMENT" PRIMARY KEY (
	"REPORT_COMMENT_CODE"
);

ALTER TABLE "P_TEAM_CONFIRM" ADD CONSTRAINT "PK_P_TEAM_CONFIRM" PRIMARY KEY (
	"P_TEAM_CONFIRM_CODE"
);

ALTER TABLE "P_REJECT" ADD CONSTRAINT "PK_P_REJECT" PRIMARY KEY (
	"P_REJECT_CODE"
);

ALTER TABLE "P_READER" ADD CONSTRAINT "PK_P_READER" PRIMARY KEY (
	"P_READER_CODE"
);

ALTER TABLE "PH_MEET_MEMBER" ADD CONSTRAINT "PK_PH_MEET_MEMBER" PRIMARY KEY (
	"PH_MEET_MEMBER_CODE"
);

ALTER TABLE "PH_CAL_PART" ADD CONSTRAINT "PK_PH_CAL_PART" PRIMARY KEY (
	"PH_CAL_PART_CODE"
);

ALTER TABLE "U_P_APPLY" ADD CONSTRAINT "PK_U_P_APPLY" PRIMARY KEY (
	"U_P_APPLY_CODE"
);

ALTER TABLE "REJECT_CONDITION" ADD CONSTRAINT "PK_REJECT_CONDITION" PRIMARY KEY (
	"REJECT_CONDITION_CODE"
);

ALTER TABLE "PH_L_VOTE_MEMBER" ADD CONSTRAINT "PK_PH_L_VOTE_MEMBER" PRIMARY KEY (
	"PH_L_VOTE_MEMBER_CODE"
);

ALTER TABLE "PH_MAINWORK_MEMBER" ADD CONSTRAINT "PK_PH_MAINWORK_MEMBER" PRIMARY KEY (
	"PH_MAINWORK_MEMBER_CODE"
);

ALTER TABLE "WARNED_POST" ADD CONSTRAINT "PK_WARNED_POST" PRIMARY KEY (
	"WARNED_POST_CODE"
);

ALTER TABLE "P_END_CONDITION" ADD CONSTRAINT "PK_P_END_CONDITION" PRIMARY KEY (
	"P_END_CONDITION_CODE"
);

ALTER TABLE "USER_NOTIFICATION" ADD CONSTRAINT "PK_USER_NOTIFICATION" PRIMARY KEY (
	"USER_NOTIFICATION_CODE"
);

ALTER TABLE "P_END" ADD CONSTRAINT "PK_P_END" PRIMARY KEY (
	"P_END_CODE"
);

ALTER TABLE "U_SKILL_PART" ADD CONSTRAINT "PK_U_SKILL_PART" PRIMARY KEY (
	"U_SKILL_PART_CODE"
);

ALTER TABLE "P_FILE" ADD CONSTRAINT "PK_P_FILE" PRIMARY KEY (
	"P_FILE_CODE"
);



